version: '2.1'
services:
  haproxy:
    image: haproxy:1.7
    mem_limit: "1024m"
    ports:
      - "80:80"
    expose:
      - "80"
    volumes:
      - ./haproxy:/usr/local/etc/haproxy
    links:
      - kong-1
      - kong-2
    depends_on: 
      kong-1:
        condition: service_healthy
      kong-2:
        condition: service_healthy
  node-app-1:
    build: .
    working_dir: /app
    links: 
      - mongo
      - redis
    depends_on: 
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "wget http://localhost:3000/status -O /dev/null || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 5
  node-app-2:
    build: .
    working_dir: /app
    links: 
      - mongo
      - redis
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "wget http://localhost:3000/status -O /dev/null || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 5
  kong-1:
    build: ./kong
    mem_limit: "1024m"
    ports:
      - "8010:8001"
    environment:
      KONG_PG_HOST: "kong-database"
    expose:
      - 7946
      - 7946/udp
    links: 
      - kong-database
    depends_on:
      kong-database:
        condition: service_healthy
      node-app-1:
        condition: service_healthy
      node-app-2:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -I -s -L http://localhost:8000 || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 5
  kong-2:
    build: ./kong
    mem_limit: "1024m"
    ports:
      - "8020:8001"
    environment:
      KONG_PG_HOST: "kong-database"
    expose:
      - 7946
      - 7946/udp
    links: 
      - kong-database
    depends_on:
      kong-database:
        condition: service_healthy
      node-app-1:
        condition: service_healthy
      node-app-2:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -I -s -L http://localhost:8000 || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 5
  kong-database:
    image: "healthcheck/postgres"
    mem_limit: "1024m"
    environment:
      POSTGRES_USER: "kong"
      POSTGRES_DB: "kong"
  mongo:
    image: "healthcheck/mongo"
    mem_limit: 1024m
  redis:
    image: "healthcheck/redis"
    mem_limit: 1024m